import { Inter } from "next/font/google";
import { ThemeProvider, Layout } from "~/components";
import { getSession } from "~/lib/auth";
import "@fontsource/inknut-antiqua";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NoNovel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [_, session] = await getSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Layout.DesktopHeader session={session} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
