import { Suspense } from "react";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import { LayoutDesktopHeader, LayoutMobileHeader } from "~/components/default";
import { LayoutFooter, ThemeProvider, AuthProvider } from "~/components/shared";
import { Toaster } from "~/components/ui/toaster";
import { Skeleton } from "~/components/ui/skeleton";

import "@smastrom/react-rating/style.css";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s | NoNovel",
    default: "NoNovel",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
  generator: "Next.js",
  applicationName: "NoNovel.io",
  referrer: "origin-when-cross-origin",
  keywords: ["novel", "fiction", "story", "public domain"],
  category: "books",
  colorScheme: "dark",
  themeColor: "black",
  creator: "Alexander Zepezauer",
  publisher: "NoNovel.io",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: "NoNovel",
    description: "Read novels online for free.",
    url: "https://nonovel.io",
    siteName: "NoNovel",
    locale: "en_US",
    type: "website",
  },
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <div className="flex flex-col min-h-screen">
              <Suspense fallback={<Skeleton className="w-full h-14" />}>
                <LayoutDesktopHeader />
                <LayoutMobileHeader />
              </Suspense>
              <main className="flex-grow">{children}</main>
              <LayoutFooter />
            </div>
            <Toaster />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
