import { Suspense } from "react";
import { Inter } from "next/font/google";
import { LayoutDesktopHeader, LayoutMobileHeader } from "~/components/default";
import { LayoutFooter, ThemeProvider, AuthProvider } from "~/components/shared";
import { Toaster } from "~/components/ui/toaster";
import { Skeleton } from "~/components/ui/skeleton";

import "@smastrom/react-rating/style.css";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NoNovel",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <div className="flex min-h-screen flex-col">
              <Suspense fallback={<Skeleton className="h-14 w-full" />}>
                <LayoutDesktopHeader />
                <LayoutMobileHeader />
              </Suspense>
              <main className="flex-grow">{children}</main>
              <LayoutFooter />
            </div>
            <Toaster />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
